added styles in line 592
osbentech/Portfolio pull request #8
Opened 2022-07-18 17:15 UTC by osbentech

here is a link to my portfolio-project https://osbentech.github.io/Portfolio/

2022-07-18 18:01 UTC, vechicin requested changes
# Hi @osbentech ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good use of GitHub Pages!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-18 18:01 UTC, vechicin commented on styles.css
When I go into the mobile version, I'm experiencing a horizontal scroll (I'm using Google Chrome, for reference). Please make sure you fix it as horizontal scrolls make for bad UI/UX/

<img width="534" alt="Screen Shot 2022-07-18 at 12 59 20" src="https://user-images.githubusercontent.com/82426682/179573541-994fa2ea-181f-4535-a83a-d022c030db6a.png">

2022-07-18 18:01 UTC, vechicin commented
https://github.com/osbentech/Portfolio/blob/41967c5ae7c14c603fd42eae8bff19a3c703d39e/README.md?plain=1#L1

Please make sure you add a Live Demo link to your README as it is a project requirement.

<img width="404" alt="Screen Shot 2022-07-18 at 13 01 35" src="https://user-images.githubusercontent.com/82426682/179573915-77bdafe7-e46a-47f0-b891-aca90c43c801.png">

2022-07-18 21:55 UTC, sumairq approved these changes
### Hi @osbentech  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ The portfolio is deployed to github pages
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-18 22:03 UTC, merged

2022-07-19 14:29 UTC, iAmWaris97 reviewed
Hi @osbentech!

Nice job so far!

I liked the styles, however, I would suggest you some changes as commented below.

Cheers and happy coding.

2022-07-19 14:29 UTC, iAmWaris97 commented on styles.css
>      border-bottom-left-radius: 20px;
Nice job!
I would suggest you change the order of the images and details of the cards as of Figma design. What do you think?